modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/Khajiitos/DontTouchMe/issues"

[[mods]]
modId = "donttouchme"
version = "${version}"
logoFile="icon.png"
displayName = "Don't Touch Me!"
authors = "Khajiitos"
displayURL="https://github.com/Khajiitos/DontTouchMe"
description = '''Client-sided mod which prevents being pushed by other entities.'''
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.donttouchme]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.donttouchme]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
